server:
  port: 8080

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    content-type: text/html
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 日志配置
logging:
  level:
    com.nbcb.template: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
